### ISSUE TITLE
A few "depends on" issues

### ISSUE THREAD

**Issue by lsv** [nuxxapp/nuxx#10]
* Its not that UX that you need to add a green to yellow - it actually took me around a minute that the green needs to be attached to the yellow. Maybe when dragging from the green then only show the yellow bubble and make the yellow a bit bigger.
* When removing a "depends on" attachment in the creator (remove the green line) it does not updates the schema, not even when pressing the schema refresh button.
* Only allow 1 connection between two of the same nodes so you dont end up with

```
---
version: 3
 
services:
  php:
    image: php:latest
    depends_on:
      - nginx
      - nginx
      - nginx
 
  nginx:
    image: nginx:latest
```
